package com.amazonaws.regions;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

class RegionDefaults {
    public static List<Region> a() {
        ArrayList arrayList = new ArrayList();
        Region region = new Region("af-south-1", "amazonaws.com");
        arrayList.add(region);
        b(region, "autoscaling", "autoscaling.af-south-1.amazonaws.com", false, true);
        b(region, "dynamodb", "dynamodb.af-south-1.amazonaws.com", false, true);
        b(region, "ec2", "ec2.af-south-1.amazonaws.com", false, true);
        b(region, "elasticloadbalancing", "elasticloadbalancing.af-south-1.amazonaws.com", false, true);
        b(region, "kms", "kms.af-south-1.amazonaws.com", false, true);
        b(region, "lambda", "lambda.af-south-1.amazonaws.com", false, true);
        b(region, "logs", "logs.af-south-1.amazonaws.com", false, true);
        b(region, "s3", "s3.af-south-1.amazonaws.com", false, true);
        b(region, "sns", "sns.af-south-1.amazonaws.com", false, true);
        b(region, "sqs", "sqs.af-south-1.amazonaws.com", false, true);
        b(region, "sts", "sts.af-south-1.amazonaws.com", false, true);
        Region region2 = new Region("ap-northeast-1", "amazonaws.com");
        arrayList.add(region2);
        b(region2, "autoscaling", "autoscaling.ap-northeast-1.amazonaws.com", false, true);
        String str = "autoscaling";
        b(region2, "cognito-identity", "cognito-identity.ap-northeast-1.amazonaws.com", false, true);
        String str2 = "cognito-identity";
        b(region2, "cognito-idp", "cognito-idp.ap-northeast-1.amazonaws.com", false, true);
        String str3 = "cognito-idp";
        b(region2, "cognito-sync", "cognito-sync.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "data.iot", "data.iot.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "dynamodb", "dynamodb.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "ec2", "ec2.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "elasticloadbalancing", "elasticloadbalancing.ap-northeast-1.amazonaws.com", false, true);
        String str4 = "elasticloadbalancing";
        b(region2, "firehose", "firehose.ap-northeast-1.amazonaws.com", false, true);
        String str5 = "firehose";
        b(region2, "iot", "iot.ap-northeast-1.amazonaws.com", false, true);
        String str6 = "iot";
        b(region2, "kinesis", "kinesis.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "kms", "kms.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "lambda", "lambda.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "logs", "logs.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "polly", "polly.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "s3", "s3.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "sdb", "sdb.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "sns", "sns.ap-northeast-1.amazonaws.com", false, true);
        String str7 = "sqs";
        b(region2, str7, "sqs.ap-northeast-1.amazonaws.com", false, true);
        b(region2, "sts", "sts.ap-northeast-1.amazonaws.com", false, true);
        Region region3 = new Region("ap-northeast-2", "amazonaws.com");
        arrayList.add(region3);
        ArrayList arrayList2 = arrayList;
        b(region3, str, "autoscaling.ap-northeast-2.amazonaws.com", false, true);
        b(region3, str2, "cognito-identity.ap-northeast-2.amazonaws.com", false, true);
        b(region3, str3, "cognito-idp.ap-northeast-2.amazonaws.com", false, true);
        String str8 = "cognito-sync";
        b(region3, str8, "cognito-sync.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "data.iot", "data.iot.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "dynamodb", "dynamodb.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "ec2", "ec2.ap-northeast-2.amazonaws.com", false, true);
        b(region3, str4, "elasticloadbalancing.ap-northeast-2.amazonaws.com", false, true);
        b(region3, str6, "iot.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "kinesis", "kinesis.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "kms", "kms.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "lambda", "lambda.ap-northeast-2.amazonaws.com", false, true);
        String str9 = "logs";
        b(region3, str9, "logs.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "polly", "polly.ap-northeast-2.amazonaws.com", false, true);
        String str10 = "s3";
        b(region3, str10, "s3.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "sns", "sns.ap-northeast-2.amazonaws.com", false, true);
        b(region3, str7, "sqs.ap-northeast-2.amazonaws.com", false, true);
        b(region3, "sts", "sts.ap-northeast-2.amazonaws.com", false, true);
        Region region4 = new Region("ap-south-1", "amazonaws.com");
        arrayList2.add(region4);
        String str11 = "amazonaws.com";
        b(region4, str, "autoscaling.ap-south-1.amazonaws.com", false, true);
        b(region4, str2, "cognito-identity.ap-south-1.amazonaws.com", false, true);
        String str12 = str3;
        b(region4, str12, "cognito-idp.ap-south-1.amazonaws.com", false, true);
        b(region4, str8, "cognito-sync.ap-south-1.amazonaws.com", false, true);
        b(region4, "dynamodb", "dynamodb.ap-south-1.amazonaws.com", false, true);
        b(region4, "ec2", "ec2.ap-south-1.amazonaws.com", false, true);
        String str13 = str4;
        b(region4, str13, "elasticloadbalancing.ap-south-1.amazonaws.com", false, true);
        b(region4, "kinesis", "kinesis.ap-south-1.amazonaws.com", false, true);
        b(region4, "kms", "kms.ap-south-1.amazonaws.com", false, true);
        b(region4, "lambda", "lambda.ap-south-1.amazonaws.com", false, true);
        b(region4, str9, "logs.ap-south-1.amazonaws.com", false, true);
        String str14 = str9;
        String str15 = "polly";
        b(region4, str15, "polly.ap-south-1.amazonaws.com", false, true);
        b(region4, str10, "s3.ap-south-1.amazonaws.com", false, true);
        b(region4, "sns", "sns.ap-south-1.amazonaws.com", false, true);
        b(region4, str7, "sqs.ap-south-1.amazonaws.com", false, true);
        b(region4, "sts", "sts.ap-south-1.amazonaws.com", false, true);
        Region region5 = new Region("ap-southeast-1", str11);
        arrayList2.add(region5);
        String str16 = str;
        String str17 = "sts";
        b(region5, str16, "autoscaling.ap-southeast-1.amazonaws.com", false, true);
        String str18 = str16;
        String str19 = str2;
        b(region5, str19, "cognito-identity.ap-southeast-1.amazonaws.com", false, true);
        b(region5, str12, "cognito-idp.ap-southeast-1.amazonaws.com", false, true);
        b(region5, str8, "cognito-sync.ap-southeast-1.amazonaws.com", false, true);
        String str20 = str8;
        String str21 = "data.iot";
        b(region5, str21, "data.iot.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "dynamodb", "dynamodb.ap-southeast-1.amazonaws.com", false, true);
        String str22 = "ec2";
        b(region5, str22, "ec2.ap-southeast-1.amazonaws.com", false, true);
        b(region5, str13, "elasticloadbalancing.ap-southeast-1.amazonaws.com", false, true);
        String str23 = str13;
        String str24 = str6;
        b(region5, str24, "iot.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "kinesis", "kinesis.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "kms", "kms.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "lambda", "lambda.ap-southeast-1.amazonaws.com", false, true);
        String str25 = str14;
        b(region5, str25, "logs.ap-southeast-1.amazonaws.com", false, true);
        b(region5, str15, "polly.ap-southeast-1.amazonaws.com", false, true);
        b(region5, str10, "s3.ap-southeast-1.amazonaws.com", false, true);
        String str26 = str10;
        b(region5, "sdb", "sdb.ap-southeast-1.amazonaws.com", false, true);
        b(region5, "sns", "sns.ap-southeast-1.amazonaws.com", false, true);
        b(region5, str7, "sqs.ap-southeast-1.amazonaws.com", false, true);
        b(region5, str17, "sts.ap-southeast-1.amazonaws.com", false, true);
        Region region6 = new Region("ap-southeast-2", str11);
        arrayList2.add(region6);
        String str27 = str18;
        b(region6, str27, "autoscaling.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str19, "cognito-identity.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str12, "cognito-idp.ap-southeast-2.amazonaws.com", false, true);
        String str28 = str12;
        String str29 = str20;
        b(region6, str29, "cognito-sync.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str21, "data.iot.ap-southeast-2.amazonaws.com", false, true);
        String str30 = str21;
        String str31 = "dynamodb";
        b(region6, str31, "dynamodb.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str22, "ec2.ap-southeast-2.amazonaws.com", false, true);
        String str32 = str29;
        String str33 = str23;
        b(region6, str33, "elasticloadbalancing.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str24, "iot.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "kinesis", "kinesis.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "kms", "kms.ap-southeast-2.amazonaws.com", false, true);
        String str34 = str24;
        String str35 = "lambda";
        b(region6, str35, "lambda.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str25, "logs.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str15, "polly.ap-southeast-2.amazonaws.com", false, true);
        String str36 = str19;
        b(region6, str26, "s3.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "sdb", "sdb.ap-southeast-2.amazonaws.com", false, true);
        b(region6, "sns", "sns.ap-southeast-2.amazonaws.com", false, true);
        b(region6, str7, "sqs.ap-southeast-2.amazonaws.com", false, true);
        String str37 = str17;
        b(region6, str37, "sts.ap-southeast-2.amazonaws.com", false, true);
        Region region7 = new Region("ca-central-1", str11);
        arrayList2.add(region7);
        b(region7, str27, "autoscaling.ca-central-1.amazonaws.com", false, true);
        b(region7, str31, "dynamodb.ca-central-1.amazonaws.com", false, true);
        b(region7, str22, "ec2.ca-central-1.amazonaws.com", false, true);
        b(region7, str33, "elasticloadbalancing.ca-central-1.amazonaws.com", false, true);
        b(region7, "kinesis", "kinesis.ca-central-1.amazonaws.com", false, true);
        b(region7, "kms", "kms.ca-central-1.amazonaws.com", false, true);
        b(region7, str35, "lambda.ca-central-1.amazonaws.com", false, true);
        b(region7, str25, "logs.ca-central-1.amazonaws.com", false, true);
        b(region7, str15, "polly.ca-central-1.amazonaws.com", false, true);
        String str38 = str15;
        String str39 = str26;
        b(region7, str39, "s3.ca-central-1.amazonaws.com", false, true);
        b(region7, "sns", "sns.ca-central-1.amazonaws.com", false, true);
        b(region7, str7, "sqs.ca-central-1.amazonaws.com", false, true);
        b(region7, str37, "sts.ca-central-1.amazonaws.com", false, true);
        Region region8 = new Region("eu-central-1", str11);
        arrayList2.add(region8);
        b(region8, str27, "autoscaling.eu-central-1.amazonaws.com", false, true);
        String str40 = str27;
        b(region8, str36, "cognito-identity.eu-central-1.amazonaws.com", false, true);
        b(region8, str28, "cognito-idp.eu-central-1.amazonaws.com", false, true);
        b(region8, str32, "cognito-sync.eu-central-1.amazonaws.com", false, true);
        b(region8, str30, "data.iot.eu-central-1.amazonaws.com", false, true);
        b(region8, str31, "dynamodb.eu-central-1.amazonaws.com", false, true);
        b(region8, str22, "ec2.eu-central-1.amazonaws.com", false, true);
        b(region8, str33, "elasticloadbalancing.eu-central-1.amazonaws.com", false, true);
        b(region8, str5, "firehose.eu-central-1.amazonaws.com", false, true);
        String str41 = str34;
        b(region8, str41, "iot.eu-central-1.amazonaws.com", false, true);
        b(region8, "kinesis", "kinesis.eu-central-1.amazonaws.com", false, true);
        b(region8, "kms", "kms.eu-central-1.amazonaws.com", false, true);
        b(region8, str35, "lambda.eu-central-1.amazonaws.com", false, true);
        b(region8, str25, "logs.eu-central-1.amazonaws.com", false, true);
        String str42 = str38;
        b(region8, str42, "polly.eu-central-1.amazonaws.com", false, true);
        b(region8, str39, "s3.eu-central-1.amazonaws.com", false, true);
        b(region8, "sns", "sns.eu-central-1.amazonaws.com", false, true);
        b(region8, str7, "sqs.eu-central-1.amazonaws.com", false, true);
        b(region8, str37, "sts.eu-central-1.amazonaws.com", false, true);
        String str43 = str11;
        Region region9 = new Region("eu-south-1", str43);
        ArrayList arrayList3 = arrayList2;
        arrayList3.add(region9);
        String str44 = str42;
        String str45 = str41;
        String str46 = "kinesis";
        String str47 = str40;
        b(region9, str47, "autoscaling.eu-south-1.amazonaws.com", false, true);
        b(region9, str31, "dynamodb.eu-south-1.amazonaws.com", false, true);
        b(region9, str22, "ec2.eu-south-1.amazonaws.com", false, true);
        b(region9, str33, "elasticloadbalancing.eu-south-1.amazonaws.com", false, true);
        b(region9, str35, "lambda.eu-south-1.amazonaws.com", false, true);
        b(region9, str25, "logs.eu-south-1.amazonaws.com", false, true);
        b(region9, str39, "s3.eu-south-1.amazonaws.com", false, true);
        b(region9, "sns", "sns.eu-south-1.amazonaws.com", false, true);
        b(region9, str7, "sqs.eu-south-1.amazonaws.com", false, true);
        b(region9, str37, "sts.eu-south-1.amazonaws.com", false, true);
        Region region10 = new Region("eu-west-1", str43);
        arrayList3.add(region10);
        b(region10, str47, "autoscaling.eu-west-1.amazonaws.com", false, true);
        b(region10, str36, "cognito-identity.eu-west-1.amazonaws.com", false, true);
        b(region10, str28, "cognito-idp.eu-west-1.amazonaws.com", false, true);
        b(region10, str32, "cognito-sync.eu-west-1.amazonaws.com", false, true);
        b(region10, str30, "data.iot.eu-west-1.amazonaws.com", false, true);
        b(region10, str31, "dynamodb.eu-west-1.amazonaws.com", false, true);
        b(region10, str22, "ec2.eu-west-1.amazonaws.com", false, true);
        b(region10, str33, "elasticloadbalancing.eu-west-1.amazonaws.com", false, true);
        b(region10, "email", "email.eu-west-1.amazonaws.com", false, true);
        b(region10, str5, "firehose.eu-west-1.amazonaws.com", false, true);
        b(region10, str45, "iot.eu-west-1.amazonaws.com", false, true);
        b(region10, str46, "kinesis.eu-west-1.amazonaws.com", false, true);
        String str48 = "kms";
        b(region10, str48, "kms.eu-west-1.amazonaws.com", false, true);
        b(region10, str35, "lambda.eu-west-1.amazonaws.com", false, true);
        b(region10, str25, "logs.eu-west-1.amazonaws.com", false, true);
        String str49 = str25;
        b(region10, "machinelearning", "machinelearning.eu-west-1.amazonaws.com", false, true);
        b(region10, str44, "polly.eu-west-1.amazonaws.com", false, true);
        b(region10, "rekognition", "rekognition.eu-west-1.amazonaws.com", false, true);
        b(region10, str39, "s3.eu-west-1.amazonaws.com", false, true);
        b(region10, "sdb", "sdb.eu-west-1.amazonaws.com", false, true);
        b(region10, "sns", "sns.eu-west-1.amazonaws.com", false, true);
        b(region10, str7, "sqs.eu-west-1.amazonaws.com", false, true);
        b(region10, str37, "sts.eu-west-1.amazonaws.com", false, true);
        Region region11 = new Region("eu-west-2", str43);
        arrayList3.add(region11);
        b(region11, str40, "autoscaling.eu-west-2.amazonaws.com", false, true);
        b(region11, str36, "cognito-identity.eu-west-2.amazonaws.com", false, true);
        b(region11, str28, "cognito-idp.eu-west-2.amazonaws.com", false, true);
        b(region11, str32, "cognito-sync.eu-west-2.amazonaws.com", false, true);
        b(region11, str31, "dynamodb.eu-west-2.amazonaws.com", false, true);
        b(region11, str22, "ec2.eu-west-2.amazonaws.com", false, true);
        b(region11, str33, "elasticloadbalancing.eu-west-2.amazonaws.com", false, true);
        b(region11, str45, "iot.eu-west-2.amazonaws.com", false, true);
        String str50 = str46;
        b(region11, str50, "kinesis.eu-west-2.amazonaws.com", false, true);
        b(region11, str48, "kms.eu-west-2.amazonaws.com", false, true);
        b(region11, str35, "lambda.eu-west-2.amazonaws.com", false, true);
        String str51 = str35;
        b(region11, str49, "logs.eu-west-2.amazonaws.com", false, true);
        String str52 = str44;
        b(region11, str52, "polly.eu-west-2.amazonaws.com", false, true);
        b(region11, str39, "s3.eu-west-2.amazonaws.com", false, true);
        b(region11, "sns", "sns.eu-west-2.amazonaws.com", false, true);
        b(region11, str7, "sqs.eu-west-2.amazonaws.com", false, true);
        b(region11, str37, "sts.eu-west-2.amazonaws.com", false, true);
        Region region12 = new Region("eu-west-3", str43);
        arrayList3.add(region12);
        ArrayList arrayList4 = arrayList3;
        String str53 = str40;
        b(region12, str53, "autoscaling.eu-west-3.amazonaws.com", false, true);
        b(region12, str31, "dynamodb.eu-west-3.amazonaws.com", false, true);
        b(region12, str22, "ec2.eu-west-3.amazonaws.com", false, true);
        b(region12, str33, "elasticloadbalancing.eu-west-3.amazonaws.com", false, true);
        b(region12, str50, "kinesis.eu-west-3.amazonaws.com", false, true);
        b(region12, str48, "kms.eu-west-3.amazonaws.com", false, true);
        String str54 = str48;
        b(region12, str51, "lambda.eu-west-3.amazonaws.com", false, true);
        String str55 = str49;
        b(region12, str55, "logs.eu-west-3.amazonaws.com", false, true);
        b(region12, str52, "polly.eu-west-3.amazonaws.com", false, true);
        b(region12, str39, "s3.eu-west-3.amazonaws.com", false, true);
        b(region12, "sns", "sns.eu-west-3.amazonaws.com", false, true);
        b(region12, str7, "sqs.eu-west-3.amazonaws.com", false, true);
        b(region12, str37, "sts.eu-west-3.amazonaws.com", false, true);
        Region region13 = new Region("sa-east-1", str43);
        arrayList4.add(region13);
        b(region13, str53, "autoscaling.sa-east-1.amazonaws.com", false, true);
        b(region13, str31, "dynamodb.sa-east-1.amazonaws.com", false, true);
        b(region13, str22, "ec2.sa-east-1.amazonaws.com", false, true);
        b(region13, str33, "elasticloadbalancing.sa-east-1.amazonaws.com", false, true);
        b(region13, str50, "kinesis.sa-east-1.amazonaws.com", false, true);
        String str56 = str50;
        b(region13, str54, "kms.sa-east-1.amazonaws.com", false, true);
        String str57 = str51;
        b(region13, str57, "lambda.sa-east-1.amazonaws.com", false, true);
        b(region13, str55, "logs.sa-east-1.amazonaws.com", false, true);
        b(region13, str52, "polly.sa-east-1.amazonaws.com", false, true);
        b(region13, str39, "s3.sa-east-1.amazonaws.com", false, true);
        String str58 = str39;
        b(region13, "sdb", "sdb.sa-east-1.amazonaws.com", false, true);
        b(region13, "sns", "sns.sa-east-1.amazonaws.com", false, true);
        b(region13, str7, "sqs.sa-east-1.amazonaws.com", false, true);
        b(region13, str37, "sts.sa-east-1.amazonaws.com", false, true);
        Region region14 = new Region("us-east-1", str43);
        ArrayList arrayList5 = arrayList4;
        arrayList5.add(region14);
        b(region14, str53, "autoscaling.us-east-1.amazonaws.com", false, true);
        String str59 = str53;
        b(region14, str36, "cognito-identity.us-east-1.amazonaws.com", false, true);
        b(region14, str28, "cognito-idp.us-east-1.amazonaws.com", false, true);
        b(region14, str32, "cognito-sync.us-east-1.amazonaws.com", false, true);
        b(region14, str30, "data.iot.us-east-1.amazonaws.com", false, true);
        b(region14, str31, "dynamodb.us-east-1.amazonaws.com", false, true);
        b(region14, str22, "ec2.us-east-1.amazonaws.com", false, true);
        b(region14, str33, "elasticloadbalancing.us-east-1.amazonaws.com", false, true);
        b(region14, "email", "email.us-east-1.amazonaws.com", false, true);
        b(region14, str5, "firehose.us-east-1.amazonaws.com", false, true);
        b(region14, str45, "iot.us-east-1.amazonaws.com", false, true);
        b(region14, str56, "kinesis.us-east-1.amazonaws.com", false, true);
        String str60 = str54;
        b(region14, str60, "kms.us-east-1.amazonaws.com", false, true);
        b(region14, str57, "lambda.us-east-1.amazonaws.com", false, true);
        b(region14, str55, "logs.us-east-1.amazonaws.com", false, true);
        String str61 = str55;
        b(region14, "machinelearning", "machinelearning.us-east-1.amazonaws.com", false, true);
        b(region14, "mobileanalytics", "mobileanalytics.us-east-1.amazonaws.com", false, true);
        b(region14, "pinpoint", "pinpoint.us-east-1.amazonaws.com", false, true);
        b(region14, str52, "polly.us-east-1.amazonaws.com", false, true);
        b(region14, "rekognition", "rekognition.us-east-1.amazonaws.com", false, true);
        b(region14, str58, "s3.amazonaws.com", false, true);
        b(region14, "sdb", "sdb.amazonaws.com", false, true);
        b(region14, "sns", "sns.us-east-1.amazonaws.com", false, true);
        b(region14, str7, "sqs.us-east-1.amazonaws.com", false, true);
        b(region14, str37, "sts.us-east-1.amazonaws.com", false, true);
        Region region15 = new Region("us-east-2", str43);
        arrayList5.add(region15);
        b(region15, str59, "autoscaling.us-east-2.amazonaws.com", false, true);
        b(region15, str36, "cognito-identity.us-east-2.amazonaws.com", false, true);
        b(region15, str28, "cognito-idp.us-east-2.amazonaws.com", false, true);
        b(region15, str32, "cognito-sync.us-east-2.amazonaws.com", false, true);
        b(region15, str31, "dynamodb.us-east-2.amazonaws.com", false, true);
        b(region15, str22, "ec2.us-east-2.amazonaws.com", false, true);
        b(region15, str33, "elasticloadbalancing.us-east-2.amazonaws.com", false, true);
        b(region15, str5, "firehose.us-east-2.amazonaws.com", false, true);
        b(region15, str45, "iot.us-east-2.amazonaws.com", false, true);
        String str62 = str56;
        b(region15, str62, "kinesis.us-east-2.amazonaws.com", false, true);
        b(region15, str60, "kms.us-east-2.amazonaws.com", false, true);
        b(region15, str57, "lambda.us-east-2.amazonaws.com", false, true);
        String str63 = str57;
        String str64 = str61;
        b(region15, str64, "logs.us-east-2.amazonaws.com", false, true);
        b(region15, str52, "polly.us-east-2.amazonaws.com", false, true);
        String str65 = str52;
        String str66 = str58;
        b(region15, str66, "s3.us-east-2.amazonaws.com", false, true);
        b(region15, "sns", "sns.us-east-2.amazonaws.com", false, true);
        b(region15, str7, "sqs.us-east-2.amazonaws.com", false, true);
        b(region15, str37, "sts.us-east-2.amazonaws.com", false, true);
        Region region16 = new Region("us-west-1", str43);
        arrayList5.add(region16);
        ArrayList arrayList6 = arrayList5;
        String str67 = str59;
        b(region16, str67, "autoscaling.us-west-1.amazonaws.com", false, true);
        b(region16, str31, "dynamodb.us-west-1.amazonaws.com", false, true);
        b(region16, str22, "ec2.us-west-1.amazonaws.com", false, true);
        b(region16, str33, "elasticloadbalancing.us-west-1.amazonaws.com", false, true);
        b(region16, str62, "kinesis.us-west-1.amazonaws.com", false, true);
        b(region16, str60, "kms.us-west-1.amazonaws.com", false, true);
        String str68 = str60;
        String str69 = str63;
        b(region16, str69, "lambda.us-west-1.amazonaws.com", false, true);
        b(region16, str64, "logs.us-west-1.amazonaws.com", false, true);
        String str70 = str64;
        String str71 = str65;
        b(region16, str71, "polly.us-west-1.amazonaws.com", false, true);
        b(region16, str66, "s3.us-west-1.amazonaws.com", false, true);
        String str72 = str66;
        b(region16, "sdb", "sdb.us-west-1.amazonaws.com", false, true);
        b(region16, "sns", "sns.us-west-1.amazonaws.com", false, true);
        b(region16, str7, "sqs.us-west-1.amazonaws.com", false, true);
        b(region16, str37, "sts.us-west-1.amazonaws.com", false, true);
        Region region17 = new Region("us-west-2", str43);
        ArrayList arrayList7 = arrayList6;
        arrayList7.add(region17);
        b(region17, str67, "autoscaling.us-west-2.amazonaws.com", false, true);
        String str73 = str43;
        b(region17, str36, "cognito-identity.us-west-2.amazonaws.com", false, true);
        b(region17, str28, "cognito-idp.us-west-2.amazonaws.com", false, true);
        b(region17, str32, "cognito-sync.us-west-2.amazonaws.com", false, true);
        b(region17, str30, "data.iot.us-west-2.amazonaws.com", false, true);
        b(region17, str31, "dynamodb.us-west-2.amazonaws.com", false, true);
        b(region17, str22, "ec2.us-west-2.amazonaws.com", false, true);
        b(region17, str33, "elasticloadbalancing.us-west-2.amazonaws.com", false, true);
        b(region17, "email", "email.us-west-2.amazonaws.com", false, true);
        b(region17, str5, "firehose.us-west-2.amazonaws.com", false, true);
        String str74 = str45;
        b(region17, str74, "iot.us-west-2.amazonaws.com", false, true);
        b(region17, str62, "kinesis.us-west-2.amazonaws.com", false, true);
        String str75 = str62;
        b(region17, str68, "kms.us-west-2.amazonaws.com", false, true);
        b(region17, str69, "lambda.us-west-2.amazonaws.com", false, true);
        String str76 = str70;
        b(region17, str76, "logs.us-west-2.amazonaws.com", false, true);
        b(region17, str71, "polly.us-west-2.amazonaws.com", false, true);
        String str77 = str71;
        b(region17, "rekognition", "rekognition.us-west-2.amazonaws.com", false, true);
        b(region17, str72, "s3.us-west-2.amazonaws.com", false, true);
        b(region17, "sdb", "sdb.us-west-2.amazonaws.com", false, true);
        b(region17, "sns", "sns.us-west-2.amazonaws.com", false, true);
        b(region17, str7, "sqs.us-west-2.amazonaws.com", false, true);
        b(region17, str37, "sts.us-west-2.amazonaws.com", false, true);
        Region region18 = new Region("cn-north-1", "amazonaws.com.cn");
        arrayList7.add(region18);
        b(region18, str67, "autoscaling.cn-north-1.amazonaws.com.cn", false, true);
        b(region18, str36, "cognito-identity.cn-north-1.amazonaws.com.cn", false, true);
        b(region18, str31, "dynamodb.cn-north-1.amazonaws.com.cn", false, true);
        b(region18, str22, "ec2.cn-north-1.amazonaws.com.cn", false, true);
        b(region18, str33, "elasticloadbalancing.cn-north-1.amazonaws.com.cn", false, true);
        b(region18, str74, "iot.cn-north-1.amazonaws.com.cn", false, true);
        String str78 = str75;
        b(region18, str78, "kinesis.cn-north-1.amazonaws.com.cn", false, true);
        b(region18, str69, "lambda.cn-north-1.amazonaws.com.cn", false, true);
        b(region18, str76, "logs.cn-north-1.amazonaws.com.cn", false, true);
        String str79 = str74;
        String str80 = str72;
        b(region18, str80, "s3.cn-north-1.amazonaws.com.cn", false, true);
        b(region18, "sns", "sns.cn-north-1.amazonaws.com.cn", false, true);
        b(region18, str7, "sqs.cn-north-1.amazonaws.com.cn", false, true);
        b(region18, str37, "sts.cn-north-1.amazonaws.com.cn", false, true);
        Region region19 = new Region("cn-northwest-1", "amazonaws.com.cn");
        arrayList7.add(region19);
        b(region19, str67, "autoscaling.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region19, str31, "dynamodb.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region19, str22, "ec2.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region19, str33, "elasticloadbalancing.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region19, str78, "kinesis.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region19, str76, "logs.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region19, str80, "s3.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region19, "sns", "sns.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region19, str7, "sqs.cn-northwest-1.amazonaws.com.cn", false, true);
        b(region19, str37, "sts.cn-northwest-1.amazonaws.com.cn", false, true);
        String str81 = str73;
        Region region20 = new Region("us-gov-west-1", str81);
        arrayList7.add(region20);
        b(region20, str67, "autoscaling.us-gov-west-1.amazonaws.com", false, true);
        b(region20, str31, "dynamodb.us-gov-west-1.amazonaws.com", false, true);
        b(region20, str22, "ec2.us-gov-west-1.amazonaws.com", false, true);
        b(region20, str33, "elasticloadbalancing.us-gov-west-1.amazonaws.com", false, true);
        b(region20, str78, "kinesis.us-gov-west-1.amazonaws.com", false, true);
        String str82 = str78;
        String str83 = str68;
        b(region20, str83, "kms.us-gov-west-1.amazonaws.com", false, true);
        b(region20, str69, "lambda.us-gov-west-1.amazonaws.com", false, true);
        b(region20, str76, "logs.us-gov-west-1.amazonaws.com", false, true);
        b(region20, "rekognition", "rekognition.us-gov-west-1.amazonaws.com", false, true);
        b(region20, str80, "s3.us-gov-west-1.amazonaws.com", false, true);
        b(region20, "sns", "sns.us-gov-west-1.amazonaws.com", false, true);
        b(region20, str7, "sqs.us-gov-west-1.amazonaws.com", false, true);
        b(region20, str37, "sts.us-gov-west-1.amazonaws.com", false, true);
        Region region21 = new Region("eu-north-1", str81);
        ArrayList arrayList8 = arrayList7;
        arrayList8.add(region21);
        b(region21, str67, "autoscaling.eu-north-1.amazonaws.com", false, true);
        b(region21, str31, "dynamodb.eu-north-1.amazonaws.com", false, true);
        b(region21, str22, "ec2.eu-north-1.amazonaws.com", false, true);
        b(region21, str33, "elasticloadbalancing.eu-north-1.amazonaws.com", false, true);
        String str84 = str33;
        b(region21, str5, "firehose.eu-north-1.amazonaws.com", false, true);
        b(region21, str79, "iot.eu-north-1.amazonaws.com", false, true);
        String str85 = str82;
        b(region21, str85, "kinesis.eu-north-1.amazonaws.com", false, true);
        b(region21, str83, "kms.eu-north-1.amazonaws.com", false, true);
        b(region21, str69, "lambda.eu-north-1.amazonaws.com", false, true);
        String str86 = str69;
        String str87 = str76;
        b(region21, str87, "logs.eu-north-1.amazonaws.com", false, true);
        b(region21, str80, "s3.eu-north-1.amazonaws.com", false, true);
        b(region21, "sns", "sns.eu-north-1.amazonaws.com", false, true);
        b(region21, str7, "sqs.eu-north-1.amazonaws.com", false, true);
        b(region21, str37, "sts.eu-north-1.amazonaws.com", false, true);
        Region region22 = new Region("ap-east-1", str81);
        arrayList8.add(region22);
        b(region22, str67, "autoscaling.ap-east-1.amazonaws.com", false, true);
        b(region22, str31, "dynamodb.ap-east-1.amazonaws.com", false, true);
        b(region22, str22, "ec2.ap-east-1.amazonaws.com", false, true);
        String str88 = str22;
        b(region22, str84, "elasticloadbalancing.ap-east-1.amazonaws.com", false, true);
        String str89 = str5;
        b(region22, str89, "firehose.ap-east-1.amazonaws.com", false, true);
        b(region22, str85, "kinesis.ap-east-1.amazonaws.com", false, true);
        b(region22, str83, "kms.ap-east-1.amazonaws.com", false, true);
        String str90 = str83;
        String str91 = str86;
        b(region22, str91, "lambda.ap-east-1.amazonaws.com", false, true);
        b(region22, str87, "logs.ap-east-1.amazonaws.com", false, true);
        String str92 = str87;
        String str93 = str77;
        b(region22, str93, "polly.ap-east-1.amazonaws.com", false, true);
        b(region22, str80, "s3.ap-east-1.amazonaws.com", false, true);
        b(region22, "sns", "sns.ap-east-1.amazonaws.com", false, true);
        b(region22, str7, "sqs.ap-east-1.amazonaws.com", false, true);
        b(region22, str37, "sts.ap-east-1.amazonaws.com", false, true);
        Region region23 = new Region("me-south-1", str81);
        arrayList8.add(region23);
        b(region23, str67, "autoscaling.me-south-1.amazonaws.com", false, true);
        b(region23, str36, "cognito-identity.me-south-1.amazonaws.com", false, true);
        b(region23, str28, "cognito-idp.me-south-1.amazonaws.com", false, true);
        b(region23, str32, "cognito-sync.me-south-1.amazonaws.com", false, true);
        b(region23, str30, "data.iot.me-south-1.amazonaws.com", false, true);
        b(region23, str31, "dynamodb.me-south-1.amazonaws.com", false, true);
        b(region23, str88, "ec2.me-south-1.amazonaws.com", false, true);
        b(region23, str84, "elasticloadbalancing.me-south-1.amazonaws.com", false, true);
        b(region23, str89, "firehose.me-south-1.amazonaws.com", false, true);
        b(region23, str79, "iot.me-south-1.amazonaws.com", false, true);
        b(region23, str85, "kinesis.me-south-1.amazonaws.com", false, true);
        b(region23, str90, "kms.me-south-1.amazonaws.com", false, true);
        b(region23, str91, "lambda.me-south-1.amazonaws.com", false, true);
        b(region23, str92, "logs.me-south-1.amazonaws.com", false, true);
        b(region23, str93, "polly.me-south-1.amazonaws.com", false, true);
        b(region23, str80, "s3.me-south-1.amazonaws.com", false, true);
        b(region23, "sdb", "sdb.me-south-1.amazonaws.com", false, true);
        b(region23, "sns", "sns.me-south-1.amazonaws.com", false, true);
        b(region23, str7, "sqs.me-south-1.amazonaws.com", false, true);
        b(region23, str37, "sts.me-south-1.amazonaws.com", false, true);
        return arrayList8;
    }

    private static void b(Region region, String str, String str2, boolean z9, boolean z10) {
        Map<String, String> h10 = region.h();
        Map<String, Boolean> b10 = region.b();
        Map<String, Boolean> c10 = region.c();
        h10.put(str, str2);
        b10.put(str, Boolean.valueOf(z9));
        c10.put(str, Boolean.valueOf(z10));
    }
}
